pipeline {
    agent any
    tools{
        maven '3.8.1'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                mvn clean install
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                mvn clean test
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}